apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: infra
resources:
- ../../base/echo-server
configMapGenerator:
- name: echo-server-values
  behavior: merge
  files:
  - values.env.yaml=values.yaml
