ingress:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-issuer
  hosts:
    - host: echo-server.my-domain.com
      paths:
        - /
  tls:
    - hosts:
        - echo-server.my-domain.com
      secretName: tls-echo-server.my-domain.com
