apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: infra
resources:
- namespace.yaml
- helm_release.yaml
configMapGenerator:
- name: echo-server-values
  files:
  - values.yaml=values.yaml
configurations:
  - kustomizeconfig.yaml
